# 官方网站
https://numpy.org/

# 安装numpy包

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# 引入numpy包

In [2]:
import numpy as np

# Array() 数组
- rank：维数
- 数据类型：bool, int, int8/16/32/64/128, float, float16/32/64, unit8/16/32/64
- 数组定义与取值
- 数据计算：+，-，*，/，**，%
- 随机数

## 数组定义与取值

In [3]:
np.arange(1, 11)  # [1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
x = np.array([[1,2,3],
              [2,3,4],
              [3,4,5],
              [4,5,6]])

In [5]:
x

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [6]:
x.dtype

dtype('int64')

In [7]:
x.ndim

2

In [8]:
x.itemsize

8

In [9]:
x.size

12

In [10]:
x.shape

(4, 3)

## 随机数

In [11]:
np.random.random((3, 4))

array([[0.10607093, 0.46787875, 0.23358762, 0.91444059],
       [0.84389353, 0.4776361 , 0.87779096, 0.19325401],
       [0.85665253, 0.54329041, 0.572704  , 0.99236035]])

In [12]:
np.random.random()

0.7662034176602663

In [13]:
np.random.randint(0, 100)

84

In [14]:
np.random.randint(0, 10, 3)

array([5, 7, 5])

In [15]:
np.random.randn(10)

array([-1.76368589, -0.32508953, -0.40267091, -1.4876239 , -0.85025943,
        0.01750899, -1.11919013,  0.9237265 , -0.84057905, -0.30837677])

In [16]:
np.random.randn(10).reshape(2, -1)

array([[-1.61140524,  0.18919981, -1.09669062, -0.88444627,  0.21320939],
       [ 0.01452065, -0.20896851,  1.14999712,  1.01386819, -0.60214152]])

### 正态分布随机数

In [17]:
np.random.randn(2, 4)

array([[-2.37852508,  0.31180439,  0.67425703,  1.41314763],
       [ 0.16343433,  0.61955313, -0.02571163,  1.61211959]])

### 指定选择项的随机数

In [18]:
np.random.choice(['red', 'green', 'blue', 'yellow'])

'blue'

### Beta分布

In [19]:
np.random.beta(1, 10, 20)

array([0.07229042, 0.14739109, 0.1117704 , 0.15806098, 0.09526338,
       0.06135585, 0.01234306, 0.05037775, 0.01773186, 0.04914897,
       0.03128014, 0.26570187, 0.09415129, 0.19563773, 0.02256162,
       0.0150194 , 0.04078929, 0.07397483, 0.00686874, 0.05485996])

## 加减乘除

### 定义数组

In [20]:
a = np.arange(0, 10).reshape(2, -1)

In [21]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
b = np.arange(10, 20).reshape(2, -1)

In [23]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 数据计算

In [24]:
a + b

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [25]:
a - b

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [26]:
a * b

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [27]:
a / b

array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421]])

In [28]:
a ** 2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [29]:
a % b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 改变数组的值

In [63]:
a = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

### 改变a中，将每行第2个数值+10

In [64]:
a[range(3), 1] += 10

In [65]:
a

array([[ 1, 12,  3],
       [ 4, 15,  6],
       [ 7, 18,  9]])

In [66]:
a[[0,1,2], [1,1,1]] += 10

In [71]:
a

array([[ 1, 22,  3],
       [ 4, 25,  6],
       [ 7, 28,  9]])

In [73]:
# find the value(s) that > 10
a[a>10]

array([22, 25, 28])

## 广播：数据计算

### 基础数据定义

In [55]:
# column N
x = np.array([[1,2,3],
              [2,3,4],
              [3,4,5],
              [4,5,6]])

In [56]:
# column N
y = np.array([1,2,3])

### 方法一：自制循环（低效的方式）

In [57]:
x1 = x.copy()
for i in range(4):
    x1[i, :] += y

In [58]:
x1

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8],
       [5, 7, 9]])

### 方法二：标准方式

In [59]:
x + np.tile(y, (4, 1))

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8],
       [5, 7, 9]])

### 方法三：广播计算方式

In [60]:
x + y

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8],
       [5, 7, 9]])

## 数组合并与拆分

In [34]:
a = np.arange(0, 10)

In [35]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.split(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [38]:
b = a.reshape(5, -1)

In [39]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
np.vstack(b)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
np.hstack(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 矩阵操作

### 引入线性矩阵

In [42]:
from numpy.linalg import *

### 矩阵初始化

In [43]:
a = np.arange(1, 5).reshape(2, -1)

In [44]:
a

array([[1, 2],
       [3, 4]])

### 逆矩阵

In [45]:
inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 矩阵转置

In [46]:
a.T

array([[1, 3],
       [2, 4]])

### 行列式

In [47]:
det(a)

-2.0000000000000004

### 特征值和特征向量

In [48]:
eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

### 二维方程求解

In [49]:
a = np.array([[1, 2], 
              [3, 4]])

In [50]:
b = np.array([[5,], [7,]])

In [51]:
solve(a, b)

array([[-3.],
       [ 4.]])

### 其它应用

#### 快速傅利叶变换

In [52]:
np.fft.fft(np.array([1, 1, 1, 1, 1, 1, 1, 1]))

array([8.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

#### 相关系数

In [53]:
np.corrcoef([1,0,1],[0,2,1])

array([[ 1.       , -0.8660254],
       [-0.8660254,  1.       ]])